### ISSUE TITLE
Incompatibility with Nicephore's "copy image to clipboard" feature

### ISSUE THREAD

**Issue by blcklghtngvg** [TeamMidnightDust/MidnightLib#7] opened 2021-12-04 20:27 UTC
Minecraft 1.18, Fabric Loader 0.12.8

Mods:
- Fabric API v0.44.0
- MidnightLib v0.3.1
- [Nicephore](https://www.curseforge.com/minecraft/mc-mods/nicephore-fabric) v1.0.0

To Reproduce:
1. Take a screenshot through Minecraft
2. Open Nicephore's screenshot GUI (H by default)
3. Click "Copy"
4. The game will crash

[crash-2021-12-04_14.13.13-client.txt](https://github.com/TeamMidnightDust/MidnightLib/files/7654628/crash-2021-12-04_14.13.13-client.txt)

**Comment by Motschen** [comment] 2022-01-03 20:14
Have you also tested this without MidnightLib?
It doesn't seem like MidnightLib is the cause of the crash.

**Comment by Motschen** [comment] 2022-01-03 20:16
The crash bug seems to have been fixed in Nicephore 1.1.1
MidnightLib wasn't the cause of this issue.
https://github.com/LotuxPunk/Nicephore-Fabric/commit/e660f52bf37b168e43956485125b448fca6b17c0

**Closed by Motschen** 2022-01-03 20:16 UTC
Labels: invalid
