### ISSUE TITLE
Using Mixins where you shouldnt causing potential crashes 1.19.2

### ISSUE THREAD

**Issue by zachsai** [TeamMidnightDust/MidnightLib#31] opened 2023-05-30 17:35 UTC
![image](https://github.com/TeamMidnightDust/MidnightLib/assets/63996164/f90681e2-fd0e-4db8-a192-6daf58e73e2f)

**Comment by Motschen** [comment] 2023-06-09 16:44
Duplicate of #19 
This has been fixed in the 1.19.4 version, but so far I haven't had the time to backport it.

**Closed as not planned by Motschen** 2023-06-09 16:44 UTC
